config/routes.rb
Rails.application.routes.draw do

  get 'transactions/new'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :registrations => "users/registrations" }
  root 'pages#index'
  get 'index' => 'pages#index'
  get 'cart' => 'pages#cart'
  get 'profile' => 'pages#profile'
  get 'admin' => 'pages#admin'
  resource :contacts, only: [:new, :create], path_names: { :new =>'' }
  resources :categories
  resources :pins, path_names: { :index =>'' }
  resources :orders
  resources :transactions, only: [:new, :create]
  
  

end

app/models/order.rb
class Order < ActiveRecord::Base
  validates :order, presence: true
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_filter :authenticate_user!, :only=>[:create, :edit, :show]

  def create 
    @order=Order.new(order_params)
    @order.email=current_user.email
    if @order.adress!='office'
      @order.order_price+=5
    end
    if @order.save
      render action: :show
    else
      @error="your cart is empty"
      redirect_to pins_path
    end
  end

  def show
    @order=Order.find(params[:id])
    gon.client_token = generate_client_token
    if (current_user.username!='admin') && (current_user.email!=@order.email)
      redirect_to pins_path
    end

  end

  def edit
    if current_user.username=='admin'
      @order=Order.find(params[:id])
    else
      redirect_to pins_path
    end
  end

  def update
    @order=Order.find(params[:id])
    if @order.update(order_params)
      redirect_to @order
    else
      render action: 'edit'
    end
  end

  private

  def order_params
    params.require(:order).permit(:order, :first_name, :last_name, :phone, :adress, :order_price, :complete)
  end
  def generate_client_token
    Braintree::ClientToken.generate
  end


end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/edit.html.erb
<div class="container">
	<div class="row">
	<div class="col-xs-2"></div>
		<div class="col-md-8 col-sm-8 col-xs-12">
			<h4>Edit order #<%=@order.id %></h4>
			</br>
			<p><b>Client information</b></p>
		    <p>Name: <%= @order.last_name%> <%= @order.first_name%></p> 
			<p>Phone: <%= @order.phone%></p>
			<p>Delivery adress: <%= @order.adress%></p>
			<p>Email: <%= @order.email%></p>
			</br>
			<%= form_for :order, url: order_path(@order), method: :put do |f| %>
				<div class="form-group">
					<%= f.label :order, class: "control-label" %> </br>
					<%= f.text_field :order, class: "form-control" %>		
				</div>
				<div class="form-group">
					<%= f.label :order_price, class: "control-label" %> </br>
					<%= f.text_field :order_price, class: "form-control" %>		
				</div>
				<div class="form-group">
					<%= f.label :phone, class: "control-label" %> </br>
					<%= f.text_field :phone, class: "form-control" %>		
				</div>
				<div class="form-group">
					<%= f.label :adress, class: "control-label" %> </br>
					<%= f.text_field :adress, class: "form-control" %>		
				</div>

				<%= f.check_box :complete %> 
				<%= f.label :complete, class: "control-label" %></p>
				</br>
				<%= f.submit "Submit", class: "btn btn-default" %>
			<% end %>
			</br>
			
		</div>
	</div>
</div>

app/views/orders/show.html.erb
<div class="container">
	<div class="row">
	<div class="col-xs-2"></div>
		<div class="col-md-8 col-sm-8 col-xs-12">
			<h2><p class="text-center">Your order</p></h2>
			<p class="text-right"><%= @order.created_at %></p>
			<% 	s1 = @order.order.split(/,/)
				@arr=[]
			    s1.each do |x|
			    	s2 = x.split(/\=/)
			      	s3=s2[0].split(/_/)
			      	arr2=[s3[1], s2[1]]
			      	@arr.push arr2
				end
				@arr.each do |item|
					item[0] = Pin.find(item[0])
				end %>
			<table class="table">
		      	<thead>
			        <tr>
			       	  <th>Product</th>
			       	  <th>Price</th>
			       	  <th>Qty</th>
			       	  <th>Sum</th>
			       	</tr>
			    </thead>
			    <tbody>
			      <%@arr.each do |item|%>
			       	<tr>
			       	  	<td class="col-md-3"><%= image_tag item[0].image.url(:thumb) %></td>
			       	  	<td><%= item[0].price %> $</td>
			       	  	<td><%= item[1] %></td>
			       	 	<td><%= item[0].price.to_f*item[1].to_i %></td>
			       	</tr>		       
			      <% end %>
			      <% if @order.adress!='office' %>
			      <tr>
			       	  <td></td>
			       	  <td></td>
			       	  <td><b>Delivery cost:<b></td>
			       	  <td>5 $</td>
			      </tr>
			      <% end %> 
			      <tr>
			       	  <td></td>
			       	  <td></td>
			       	  <td><b>Total price:<b></td>
			       	  <td><%= @order.order_price %></td>
			       </tr>
		    	</tbody>
		    </table>
		    </br>
		    <p><b>Client information</b></p>
		    <p>Name: <%= @order.last_name%> <%= @order.first_name%></p> 
			<p>Phone: <%= @order.phone%></p>
			<p>Delivery adress: <%= @order.adress%></p>
			<p>Email: <%= @order.email%></p>
			<% if current_user.username=='admin' %>
				<a href="<%= edit_order_path(@order) %>" class="btn btn-default" role="button">Edit order</a>
			<% else %>
				
				
			<% end %>
<div class="form-container radius-box glassy-bg small-10 small-centered medium-8 large-6 columns">
  <h2 class="mbs">New Transaction</h2>
  <%= form_tag transactions_path do%>
    <p>Please enter your payment details:</p>
    <div id="payment-form"></div>
    <%=submit_tag "Pay #{@order.order_price}$", class: "button mt1" %>
  <%end%>
</div>

<script>
	braintree.setup(gon.client_token, 'payment-form', { container: 'payment-form' });
  
</script>
		</div>
	</div>
</div>

<script type="text/javascript">
  $(function(){
    cancel_order();
  });
</script>