config/routes.rb
Rails.application.routes.draw do

  get 'transactions/new'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :registrations => "users/registrations" }
  root 'pages#index'
  get 'index' => 'pages#index'
  get 'cart' => 'pages#cart'
  get 'profile' => 'pages#profile'
  get 'admin' => 'pages#admin'
  resource :contacts, only: [:new, :create], path_names: { :new =>'' }
  resources :categories
  resources :pins, path_names: { :index =>'' }
  resources :orders
  resources :transactions, only: [:new, :create]
  
  

end

app/views/pages/admin.html.erb
<div class="container">
	<div class="row">
	<div class="col-xs-2"></div>
		<div class="col-md-8 col-sm-8 col-xs-12">
			<h2><p class="text-center">admin</p></h2>
			</br>
			<div>
			<ul id="myTabs" class="nav nav-tabs" role="tablist"> 
				<li role="presentation" class="active"><a href="#home" id="home-tab" role="tab" data-toggle="tab" aria-controls="home" aria-expanded="true">Current Orders</a></li>
				<li role="presentation" class=""><a href="#complete_order" id="order-tab" role="tab" data-toggle="tab" aria-controls="complete_order" aria-expanded="true">Complete Orders</a></li>
				<li role="presentation" class=""><a href="#contacts" id="contacts-tab" role="tab" data-toggle="tab" aria-controls="contacts" aria-expanded="true">Contacts</a></li>  
				<li role="presentation" class=""><a href="#profile" role="tab" id="profile-tab" data-toggle="tab" aria-controls="profile" aria-expanded="false">Profile</a></li>  
			</ul>
			<div id="myTabContent" class="tab-content">
				<div role="tabpanel" class="tab-pane fade active in" id="home" aria-labelledby="home-tab">
					<h4>Current orders:</h4>
					<table class="table">
				      	<thead>
					        <tr>
					       	  <th>#</th>
					       	  <th># order</th>
					       	  <th>Qty</th>
					       	  <th>Sum</th>
					       	  <th>Delivery adress</th>
					       	</tr>
					    </thead>
					    <tbody>
					    	<% i=0 %>
							<% @orders.each do |order| %>
								<% if order.complete==false %>
									<% i+=1
									s1 = order.order.split(/,/)
									@arr=[]
									qty=0
								    s1.each do |x|
								    	s2 = x.split(/\=/)
								      	s3=s2[0].split(/_/)
								      	arr2=[s3[1], s2[1]]
								      	@arr.push arr2
									end
									@arr.each do |item|
										qty += item[1].to_i
									end %>
									<tr>
					       	  			<td class="col-md-1"><b><%= i %></b></td>
					       	  			<td class="col-md-3"><%= link_to "#{order.id} at #{order.created_at} (see details)", order_path(order)%></td>
					       	  			<td class="col-md-1"><%= qty %></td>
					       	 			<td class="col-md-1"><%= order.order_price %></td>
					       	 			<td><%= order.adress %></td>
					       			</tr>
								<% end %>
							<% end %>
						</tbody>
				    </table>
				</div>
				<div role="tabpanel" class="tab-pane fade" id="complete_order" aria-labelledby="order-tab"> 
					<h4>Complete orders:</h4>
					<table class="table">
				      	<thead>
					        <tr>
					       	  <th>#</th>
					       	  <th># order</th>
					       	  <th>Complete date</th>
					       	  <th>Qty</th>
					       	  <th>Sum</th>
					       	  <th>Delivery adress</th>
					       	</tr>
					    </thead>
					    <tbody>
					    	<% i=0 %>
							<% @orders.each do |order| %>
								<% if order.complete %>
									<% i+=1
									s1 = order.order.split(/,/)
									@arr=[]
									qty=0
								    s1.each do |x|
								    	s2 = x.split(/\=/)
								      	s3=s2[0].split(/_/)
								      	arr2=[s3[1], s2[1]]
								      	@arr.push arr2
									end
									@arr.each do |item|
										qty += item[1].to_i
									end %>
									<tr>
					       	  			<td class="col-md-1"><%= i %></td>
					       	  			<td class="col-md-3"><%= link_to "#{order.id} at #{order.created_at} (see details)", order_path(order)%></td>
					       	  			<td class="col-md-2"><%= order.updated_at %></td>
					       	  			<td class="col-md-1"><%= qty %></td>
					       	 			<td class="col-md-1"><%= order.order_price %></td>
					       	 			<td><%= order.adress %></td>
					       			</tr>
								<% end %>
							<% end %>
						</tbody>
				    </table> 
				</div>
				<div role="tabpanel" class="tab-pane fade" id="contacts" aria-labelledby="contacts-tab"> 
					<h4>Contacts:</h4>
					<table class="table">
						<thead>
					        <tr>
					       	  <th>#</th>
					       	  <th>Email</th>
					       	  <th>Name</th>
					       	  <th>Date</th>
					       	  <th>Message</th>
					       	</tr>
					    </thead>
					    <tbody>
					    	<% i=0 %>
					    	<% @contacts.each do |contact| %>
					    		<% i+=1 %>
					    		<tr>
					       	  		<td class="col-md-1"><%= i %></td>
					       	  		<td class="col-md-2"><%= contact.email %></td>
					       	  		<td class="col-md-1"><%= contact.name %></td>
					       	 		<td class="col-md-2"><%= contact.created_at %></td>
					       	 		<td><%= contact.message %></td>
					       		</tr>	
					    	<% end %>
					    </tbody>	
					</table>
				</div> 
				<div role="tabpanel" class="tab-pane fade" id="profile" aria-labelledby="profile-tab"> 
					<%= render :template => "devise/registrations/edit" %> 
				</div> 
			</div>
			</div>
		</div>
	</div>
</div>

app/views/pages/cart.html.erb
<div class="container">
	<div class="row">
	<div class="col-xs-2"></div>
		<div class="col-md-8 col-sm-8 col-xs-12">
			<h2>cart</h2>
			<table id="OrdersTable" class="table table-condensed">
			</table>
			<%= form_for :order, url: orders_path do |f| %>
				<div class="form-group">
			          <%= f.hidden_field :order, id: "orders_input", class: "form-control" %>
			    </div>
			    <div class="form-group">
			          <%= f.hidden_field :order_price, id: "order_price", class: "form-control" %>
			    </div>
			    <div class="form-group">
			          <%= f.label :first_name, class: "control-label" %>
			          <%= f.text_field :first_name, :value => current_user.first_name, class: "form-control" %>
			    </div>
			    <div class="form-group">
			          <%= f.label :last_name, class: "control-label" %>
			          <%= f.text_field :last_name, :value => current_user.last_name, class: "form-control" %>
			    </div>
			    <div class="form-group">
			          <%= f.label :phone, class: "control-label" %>
			          <%= f.text_field :phone, :value => current_user.phone, class: "form-control" %>
			    </div>
			    <div class="form-group">
			          <%= f.label :adress, class: "control-label" %>
			          <%= f.select :adress, options_for_select(["office", "#{current_user.adress} +5$"]), {}, {class: "form-control"} %>
			    </div>

			    <%= f.submit "Order", class: "btn btn btn-default", id: "order_button"%>
			<% end %>
		</div>
	</div>
</div>
<script type="text/javascript">
  $(function(){
    update_orders_link();
    update_orders_input();
    add_order_table();
    update_order_price_input()
  });
</script>

app/views/pages/index.html.erb
<h1>Index page</h1>

app/views/pages/profile.html.erb
<div class="container">
	<div class="row">
	<div class="col-xs-2"></div>
		<div class="col-md-8 col-sm-8 col-xs-12">
			<h2><p class="text-center"><%= current_user.username%> profile</p></h2>
			</br>
			<div>
			<ul id="myTabs" class="nav nav-tabs" role="tablist"> 
				<li role="presentation" class="active"><a href="#home" id="home-tab" role="tab" data-toggle="tab" aria-controls="home" aria-expanded="true">Orders</a></li> 
				<li role="presentation" class=""><a href="#profile" role="tab" id="profile-tab" data-toggle="tab" aria-controls="profile" aria-expanded="false">Profile</a></li>  
			</ul>
			<div id="myTabContent" class="tab-content">
				<div role="tabpanel" class="tab-pane fade active in" id="home" aria-labelledby="home-tab">
					<h4>Current orders:</h4>
					<table class="table">
				      	<thead>
					        <tr>
					       	  <th>#</th>
					       	  <th># order</th>
					       	  <th>Qty</th>
					       	  <th>Sum</th>
					       	  <th>Delivery adress</th>
					       	</tr>
					    </thead>
					    <tbody>
					    	<% i=0 %>
							<% @orders.each do |order| %>
								<% if order.complete==false %>
									<% i+=1
									s1 = order.order.split(/,/)
									@arr=[]
									qty=0
								    s1.each do |x|
								    	s2 = x.split(/\=/)
								      	s3=s2[0].split(/_/)
								      	arr2=[s3[1], s2[1]]
								      	@arr.push arr2
									end
									@arr.each do |item|
										qty += item[1].to_i
									end %>
									<tr>
					       	  			<td class="col-md-1"><b><%= i %></b></td>
					       	  			<td class="col-md-2"><%= link_to "#{order.id} at #{order.created_at} (see details)", order_path(order)%></td>
					       	  			<td class="col-md-1"><%= qty %></td>
					       	 			<td class="col-md-1"><%= order.order_price %></td>
					       	 			<td><%= order.adress %></td>
					       			</tr>
								<% end %>
							<% end %>
						</tbody>
				    </table>
					</br>
					<h4>Complete orders:</h4>
					<table class="table">
				      	<thead>
					        <tr>
					       	  <th>#</th>
					       	  <th># order</th>
					       	  <th>Qty</th>
					       	  <th>Sum</th>
					       	  <th>Delivery adress</th>
					       	</tr>
					    </thead>
					    <tbody>
					    	<% i=0 %>
							<% @orders.each do |order| %>
								<% if order.complete %>
									<% i+=1
									s1 = order.order.split(/,/)
									@arr=[]
									qty=0
								    s1.each do |x|
								    	s2 = x.split(/\=/)
								      	s3=s2[0].split(/_/)
								      	arr2=[s3[1], s2[1]]
								      	@arr.push arr2
									end
									@arr.each do |item|
										qty += item[1].to_i
									end %>
									<tr>
					       	  			<td class="col-md-1"><%= i %></td>
					       	  			<td class="col-md-2"><%= link_to "#{order.id} (see details)", order_path(order)%></td>
					       	  			<td class="col-md-1"><%= qty %></td>
					       	 			<td class="col-md-1"><%= order.order_price %></td>
					       	 			<td><%= order.adress %></td>
					       			</tr>
								<% end %>
							<% end %>
						</tbody>
				    </table>
				</div>
				<div role="tabpanel" class="tab-pane fade" id="profile" aria-labelledby="profile-tab"> 
					<%= render :template => "devise/registrations/edit" %> 
				</div> 
			</div>
			</div>
		</div>
	</div>
</div>