config/routes.rb
Rails.application.routes.draw do

  get 'transactions/new'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :registrations => "users/registrations" }
  root 'pages#index'
  get 'index' => 'pages#index'
  get 'cart' => 'pages#cart'
  get 'profile' => 'pages#profile'
  get 'admin' => 'pages#admin'
  resource :contacts, only: [:new, :create], path_names: { :new =>'' }
  resources :categories
  resources :pins, path_names: { :index =>'' }
  resources :orders
  resources :transactions, only: [:new, :create]
  
  

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :pins
  validates :title, presence: true, length: { maximum: 50 }
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_filter :authenticate_user!, :only=>[:new, :create, :index]
  def index
    redirect_to pins_path
  end

  def new
    if current_user.username=='admin'
      
    else
      redirect_to pins_path

    end
  end

  def show
    @categories=Category.all
    @category=Category.find(params[:id])
  end

  def create
    @category=Category.new(category_params)
    if @category.save
      redirect_to index_path
    else
      render action: 'new'
    end
  end

  private

  def category_params
    params.require(:category).permit(:title)
  end

end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/new.html.erb
<h2>Add category</h2>
<%= form_for :category, url: categories_path do |f| %>
				<% if @category && @category.errors.any? %>
					<p>
					<% @error=@category.errors.full_messages.first %>
					</p>
				<% end %>

			   	<div class="form-group">
					<%= f.label :title, class: "control-label" %> </br>
					<%= f.text_field :title, class: "form-control" %>		
				</div>
				</br>
				<%= f.submit "Submit", class: "btn btn-default" %>
<% end %>

app/views/categories/show.html.erb
<div class="container">
	<div class="row">
	<div class="col-xs-2">
    <div class="row">
      <h2><p class="text-center">Category</p></h2>
    </div>
    <table class="table table-hover">
    <tbody>
    <tr><td>
        <%= link_to "All", pins_path %>
    </td></tr>
    <% @categories.each do |category| %>
      <tr><td>
        <%= link_to "#{category.title}", category %>
      </td></tr>
    <% end %>
    </tbody>
    </table>  
  </div>
		<div class="col-md-8 col-sm-8 col-xs-12">
			<h2><p class="text-center"><%= @category.title %></p></h2>
			<div class="row">
				<% @category.pins.each do |pin| %>
					<div class="col-sm-6 col-md-6">
    					<div class="thumbnail">
      						<%= link_to image_tag(pin.image.url(:medium)),pin_path(pin), class: "center-block img-thumbnail" %>
      						<div class="caption">
        						<h3><p class="text-center"><%= link_to pin.label,pin_path(pin) %></p></h3>
        						<p><b>Price: <%=pin.price %> $</b></p>
        						</br>
        						<p>Material: <%=pin.material %></p>
                    </br>
        						<p><a href="" class="btn btn-default btn-sm" role="button" onclick="add_to_cart(<%=pin.id%>, '<%= pin.label %>', <%= pin.price %>)">Add to Cart (<%= pin.price %>$)</a></p>
      						</div>
              <% if user_signed_in? %>
                <% if current_user.username=='admin' %>
    					     <%= link_to 'edit',edit_pin_path(pin) %>
                <% end %>
              <% end %>
              </div>
  					</div>
				<% end %>
			</div>
    </div>
	</div>
</div>