config/routes.rb
Rails.application.routes.draw do

  get 'transactions/new'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :registrations => "users/registrations" }
  root 'pages#index'
  get 'index' => 'pages#index'
  get 'cart' => 'pages#cart'
  get 'profile' => 'pages#profile'
  get 'admin' => 'pages#admin'
  resource :contacts, only: [:new, :create], path_names: { :new =>'' }
  resources :categories
  resources :pins, path_names: { :index =>'' }
  resources :orders
  resources :transactions, only: [:new, :create]
  
  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PinShop</title>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
  <script data-require="bootstrap@*" data-semver="3.3.6" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.js"></script>
  <link data-require="bootstrap-css@*" data-semver="3.3.6" rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.css" />
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <script src="https://code.jquery.com/jquery-2.1.3.js"></script>
  <script src="js/bootstrap.js"></script>
  <%= include_gon %>
  <%= stylesheet_link_tag "application" %>
  <%= javascript_include_tag "vendor/modernizr" %>
  <%= csrf_meta_tags %>
  <script src="https://js.braintreegateway.com/js/braintree-2.20.0.min.js"></script>
</head>

<body>

<div class="container">

      <!-- Static navbar -->
      <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>            
          </button>
          <a class="navbar-brand" href="/"><b>Ufleku PinShop</font></b></a>
        </div>
        <div class="collapse navbar-collapse navbar-collapse" id="myNavbar"> 
          <ul class="nav navbar-nav">
            <li><%= link_to 'Shop', pins_path %><li>
            <li><%= link_to 'Contacts', contacts_path %><li>
            <li><%= link_to 'CART', cart_path, id: "orders_link" %><li>
          </ul>
          <ul class="nav navbar-nav navbar-right" >
              <% if user_signed_in? %>
                <li role="presentation" class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
                <%= current_user.username %>
                <% if current_user.username=='admin' %> 
                  (<%= Order.where("complete=?", false).count %>)
                <% end %>
                <span class="caret"></span></a>
                <ul class="dropdown-menu">
                <% if current_user.username=='admin' %>
                  <li><a href="<%= admin_path %>">Admin page (<%= Order.where("complete=?", false).count %>)</a></li>
                  <li role="separator" class="divider"></li>
                  <li><%= link_to 'Add new Pin', new_pin_path  %><li>
                  <li><%= link_to 'Add new Category', new_category_path  %><li>
                <% else %>  
                  <li><a href="<%= profile_path %>"><%= current_user.username %>'s Profile</a></li>
                <% end %>
                 <li role="separator" class="divider"></li>
                <li><%= link_to 'Sign out', destroy_user_session_path, method: :delete %></li>
                </ul>
              <% else %>
                <li ><a href="#" data-toggle="modal" data-target="#SignModal">Sign in</a></li>
              <% end %>
          </ul>
        </div>
        </div>
      </nav>

<%if @error && @error.length > 0 then %>
  <div class="alert alert-danger"><%=@error%></div>
<% end %>
<%if alert  then %>
  <div class="alert alert-danger"><%= alert%></div>
<% end %>
<%if notice then %>
  <div class="alert alert-success"><%= notice %></div>
<% end %>

<%= yield %>


<div class="modal fade" id="SignModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">                                                                              
              <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
              <h4 class="modal-title" id="exampleModalLabel">Log in</h4>
            </div>
              <%= form_for(User.new, url: session_path(:user)) do |f| %>
                <div class="modal-body">
                <div class="form-group">
                    <%= f.label :email, class: "control-label", id: "control-label" %><br />
                    <%= f.email_field :email, autofocus: true, class: "form-control", placeholder: 'Email' %>
                </div>

                <div class="form-group">
                    <%= f.label :password, class: "control-label", id: "control-label" %><br />
                    <%= f.password_field :password, autocomplete: "off", class: "form-control", placeholder: 'Password' %>
                </div>

                <% if devise_mapping.rememberable? -%>
                    <div class="form-group">
                      <%= f.check_box :remember_me %>
                      <%= f.label :remember_me, class: "control-label", id: "control-label" %>
                    </div>
                <% end -%>
                <a href="<%= user_omniauth_authorize_path(:facebook) %>" class="btn btn-primary btn-sm">Sign in with Facebook</a>
                <a href="<%= user_omniauth_authorize_path(:vkontakte) %>" class="btn btn-primary btn-sm">Sign in with Vkontakte</a>
                <hr>
                <p id="control-label"><%= link_to "Sign up", new_registration_path(resource_name), id: "control-label" %> |
                <%= link_to "Forgot your password?", new_password_path(resource_name), id: "control-label" %></p>
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                  <%= f.submit "Log in", class: "btn btn-success" %>
                </div>
            <% end %>
          </div>
        </div>
      </div>

<script type="text/javascript">
  $(function(){
    update_orders_link();
    update_orders_input();
    
  });
  $('#SignModal').on('show.bs.modal', function (event) {
        
});
</script>

</body>
</html>